# Generated by Django 5.0.3 on 2024-06-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='telegram_id',
            field=models.PositiveBigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
