# Generated by Django 5.0.3 on 2024-06-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='telegram_id',
        ),
    ]
