# Generated by Django 5.0.3 on 2024-06-17 10:07

import django.db.models.deletion
import products.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to=products.helpers.SaveMediaFiles.testimonial)),
                ('client_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.helpers.SaveMediaFiles.blog_image)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('who', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['id'], name='products_bl_id_6877eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.helpers.SaveMediaFiles.product_image)),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('price', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
                ('price_type', models.CharField(choices=[('EURO', 'EURO'), ('$', '$'), ('SO`M', 'SO`M')], max_length=4)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['id'], name='products_pr_id_b46934_idx')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.helpers.SaveMediaFiles.clientcomment_image)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('staff_type', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=80)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['id'], name='products_te_id_38c776_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.helpers.SaveMediaFiles.clientcomment_image)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['id'], name='products_co_id_74a227_idx')],
            },
        ),
    ]
