# Generated by Django 5.0.3 on 2024-06-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_products_pr_id_b46934_idx_products_id_5ad420_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_id_758ccd_idx',
            old_name='products_co_id_74a227_idx',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
