# Generated by Django 5.0.3 on 2024-06-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_products_co_id_74a227_idx_comments_id_758ccd_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blog',
            new_name='blogs_id_54dbe7_idx',
            old_name='products_bl_id_6877eb_idx',
        ),
        migrations.RenameIndex(
            model_name='team',
            new_name='teams_id_2236c1_idx',
            old_name='products_te_id_38c776_idx',
        ),
        migrations.AlterModelTable(
            name='blog',
            table='blogs',
        ),
        migrations.AlterModelTable(
            name='team',
            table='teams',
        ),
    ]
