# Generated by Django 5.0.3 on 2024-06-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_products_bl_id_6877eb_idx_blogs_id_54dbe7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=30, null=True, unique=True)),
                ('telegram_id', models.PositiveBigIntegerField(unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
