# Generated by Django 5.0.3 on 2024-06-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50, verbose_name='Maxsulot nomi ')),
                ('photo', models.CharField(max_length=200, verbose_name='Rasm file_id')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx')),
                ('description', models.TextField(max_length=300, verbose_name='Maxsulto xaqida')),
                ('category_code', models.CharField(max_length=30, verbose_name='Category code')),
                ('category_name', models.CharField(max_length=40, verbose_name='Kategoriya nomi')),
                ('subcategory_code', models.CharField(max_length=50, verbose_name='Ost_categoriya kodi')),
                ('subcategory_name', models.CharField(max_length=50, verbose_name='Ost-kategoriya nomi')),
            ],
            options={
                'db_table': 'products_product',
            },
        ),
        migrations.CreateModel(
            name='ProductsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='Full name')),
                ('username', models.CharField(max_length=20, null=True, unique=True, verbose_name='Username')),
                ('telegram_id', models.PositiveBigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products_users',
            },
        ),
    ]
