# Generated by Django 5.0.3 on 2024-06-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productsproducts_productsusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsusers',
            old_name='created_date',
            new_name='create_date',
        ),
        migrations.RemoveField(
            model_name='productsproducts',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='productsproducts',
            name='product_name',
        ),
        migrations.AddField(
            model_name='productsproducts',
            name='name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsproducts',
            name='category_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='productsproducts',
            name='category_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='productsproducts',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productsproducts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productsproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='productsproducts',
            name='subcategory_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='productsproducts',
            name='subcategory_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='productsusers',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productsusers',
            name='telegram_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='productsusers',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
